services:
  - type: web
    name: myesther
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k gevent -w 1 server:app"
    envVars:
      - key: PORT
        value: 5000
